# Generated by Django 5.2.8 on 2025-11-23 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('tracking_id', models.CharField(default='PKG-E3CB6696', editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('size', models.IntegerField()),
                ('destination', models.CharField(max_length=200)),
                ('is_fragile', models.BooleanField(default=False, help_text='Handle with care if True')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=50)),
                ('bin_id', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('INGESTED', 'Ingested on Conveyor'), ('STORED', 'Stored in Bin'), ('LOADED', 'Loaded on Truck'), ('UNLOADED', 'Unloaded from Truck'), ('ERROR', 'Error')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageBin',
            fields=[
                ('bin_id', models.CharField(default='BIN-0A662929', editable=False, max_length=50, primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(help_text='Volume capacity of the bin')),
                ('is_occupied', models.BooleanField(default=False)),
                ('current_tracking_id', models.CharField(blank=True, help_text='Tracking ID of the package currently in this bin', max_length=100, null=True)),
            ],
            options={
                'ordering': ['capacity'],
                'indexes': [models.Index(fields=['capacity'], name='warehouse_s_capacit_44b025_idx')],
            },
        ),
    ]
