# Generated by Django 5.2.8 on 2025-11-23 19:28

import warehouse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracking_id',
            field=models.CharField(default=warehouse.models.generate_tracking_id, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='bin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
